import { useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react';
import { Link } from 'react-router-dom';
import gsap from 'gsap';
import { cycleStages } from '../data/cycle';
import { motion } from '../motionTokens';
import { markGameDone } from '../utils/progress';
import { shouldShowCongratsAfterCompletion, syncCongratsCycle } from '../utils/congrats';
import { CongratsModal } from '../components/CongratsModal';
import './CycleGamePage.css';

type DragState = { stageId: string; x: number; y: number };
const shuffle = <T,>(items: T[]) => [...items].sort(() => Math.random() - 0.5);
const reduceMotion = () => window.matchMedia('(prefers-reduced-motion: reduce)').matches;

export function CycleGamePage() {
  const completionRecorded = useRef(false);
  const [showCongrats, setShowCongrats] = useState(false);
  const rootRef = useRef<HTMLElement | null>(null);
  const [round, setRound] = useState<1 | 2>(1); const [waiting, setWaiting] = useState(() => shuffle(cycleStages)); const [placed, setPlaced] = useState<string[]>([]); const [selected, setSelected] = useState<string | null>(null); const [drag, setDrag] = useState<DragState | null>(null); const [mistakes, setMistakes] = useState(0); const [hint, setHint] = useState(''); const [time, setTime] = useState(0); const [started, setStarted] = useState(false); const [phaseMessage, setPhaseMessage] = useState(''); const [complete, setComplete] = useState(false);
  useEffect(() => { if (!started || complete) return; const timer = window.setInterval(() => setTime((value) => value + 1), 1000); return () => window.clearInterval(timer); }, [started, complete]);
  useEffect(() => { syncCongratsCycle(); }, []);
  useEffect(() => { if (!complete || completionRecorded.current) return; completionRecorded.current = true; if (shouldShowCongratsAfterCompletion(markGameDone('vong-nhan-thuc'))) setShowCongrats(true); }, [complete]);
  useEffect(() => { if (placed.length !== cycleStages.length) return; setPhaseMessage('Vòng nhận thức lặp lại ở mức cao hơn: hiểu sâu hơn sau mỗi lần thực tiễn.'); const timer = window.setTimeout(() => { if (round === 1) { setRound(2); setWaiting(shuffle(cycleStages)); setPlaced([]); setSelected(null); setPhaseMessage(''); } else setComplete(true); }, 1000); return () => window.clearTimeout(timer); }, [placed, round]);
  useEffect(() => { if (!drag) return; const move = (event: PointerEvent) => setDrag((current) => current ? { ...current, x: event.clientX, y: event.clientY } : null); const end = (event: PointerEvent) => { const target = event.target instanceof Element ? event.target.closest<HTMLElement>('[data-cycle-slot]') : null; const slot = target?.dataset.cycleSlot; if (slot) placeCard(drag.stageId, slot); else setDrag(null); }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', end, { once: true }); return () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', end); }; }, [drag]);
  const begin = () => { if (!started) setStarted(true); };
  const placeCard = (stageId: string, slotId: string) => { begin(); if (placed.includes(slotId)) return; if (stageId === slotId) { setPlaced((value) => [...value, slotId]); setWaiting((value) => value.filter((stage) => stage.id !== stageId)); setSelected(null); setDrag(null); setHint(''); if (!reduceMotion()) { const node = rootRef.current?.querySelector<HTMLElement>(`[data-cycle-slot="${slotId}"]`); if (node) gsap.fromTo(node, { scale: 0.96 }, { scale: 1, duration: motion.duration.fast, ease: motion.easing.enter }); } } else { const stage = cycleStages.find((item) => item.id === stageId); setMistakes((value) => value + 1); setHint(stage?.hint ?? 'Hãy xem lại thứ tự của vòng nhận thức.'); setSelected(null); setDrag(null); if (!reduceMotion()) { const node = rootRef.current?.querySelector<HTMLElement>(`[data-cycle-card="${stageId}"]`); if (node) gsap.fromTo(node, { x: -6 }, { x: 6, duration: motion.duration.instant, yoyo: true, repeat: 3, ease: motion.easing.standard }); } } };
  const onCardPointerDown = (event: ReactPointerEvent<HTMLButtonElement>, stageId: string) => { event.preventDefault(); begin(); setSelected(stageId); setDrag({ stageId, x: event.clientX, y: event.clientY }); };
  const reset = () => { setRound(1); setWaiting(shuffle(cycleStages)); setPlaced([]); setSelected(null); setDrag(null); setMistakes(0); setHint(''); setTime(0); setStarted(false); setPhaseMessage(''); setComplete(false); };
  const cardText = (stageId: string) => { const stage = cycleStages.find((item) => item.id === stageId)!; return round === 1 ? stage.title : stage.example; };
  return <><main className="game-page cycle-page" ref={rootRef}><nav className="topnav"><Link to="/">FPT<span>•</span>PHIL</Link><Link to="/game">← Chọn game</Link></nav><header className="game-hero"><p className="eyebrow">Luyện quy trình nhận thức · Vòng {round}/2</p><h1>Vòng<br/><mark>nhận thức.</mark></h1><p>Xếp các thẻ theo hành trình từ thực tiễn đến nhận thức, rồi quay lại thực tiễn để kiểm nghiệm.</p></header><section className="game-board cycle-board-shell"><div className="game-stats"><span>Đúng <b>{placed.length}/{cycleStages.length}</b></span><span>Đặt sai <b>{mistakes}</b></span><span>Thời gian <b>{time}s</b></span></div>{!complete ? <><div className="cycle-slots">{cycleStages.map((stage, index) => <button key={stage.id} data-cycle-slot={stage.id} className={`cycle-slot slot-${index + 1} ${placed.includes(stage.id) ? 'is-filled' : ''}`} onClick={() => selected && placeCard(selected, stage.id)} disabled={placed.includes(stage.id)}><small>{index + 1}</small><strong>{stage.title}</strong>{placed.includes(stage.id) && <span className="placed-card">{cardText(stage.id)}</span>}</button>)}</div><div className="cycle-arrows" aria-hidden="true"><span>→</span><span>↓</span><span>←</span><span>↺</span></div><div className="cycle-waiting" aria-label="Thẻ cần xếp">{waiting.map((stage) => <button key={stage.id} data-cycle-card={stage.id} className={`cycle-card ${selected === stage.id ? 'is-selected' : ''}`} onPointerDown={(event) => onCardPointerDown(event, stage.id)} onClick={() => { begin(); setSelected(stage.id); }}>{cardText(stage.id)}</button>)}</div>{hint && <p className="cycle-hint">Gợi ý: {hint}</p>}{phaseMessage && <p className="cycle-message">{phaseMessage}</p>}{drag && <span className="cycle-drag-preview" style={{ transform: `translate3d(${drag.x + 14}px, ${drag.y + 14}px, 0)` }}>{cardText(drag.stageId)}</span>}</> : <div className="game-result"><p className="eyebrow">Hoàn thành cả 02 vòng</p><h2>Bạn đã đi hết<br/>một vòng nhận thức.</h2><p><b>{mistakes}</b> lần đặt sai · <b>{time}</b> giây</p><button className="primary-btn" onClick={reset}>Chơi lại ↺</button></div>}</section></main><CongratsModal open={showCongrats} onClose={() => setShowCongrats(false)} /></>;
}
